// Copyright (c) 2026 Anup Ranjan. Licensed under Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
package com.search.api.config;

import io.lettuce.core.ClientOptions;
import io.lettuce.core.SslOptions;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.data.redis.autoconfigure.LettuceClientConfigurationBuilderCustomizer;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * NR-155: encryption in transit to Redis. Redis's self-signed cert
 * (Bitnami's autoGenerated CA) isn't in any trust bundle this app has
 * configured, so default Lettuce SSL peer verification would reject every
 * connection. Disabling verification here still encrypts the channel — the
 * property this closes ("TLS on Redis") is about traffic not being
 * plaintext on the wire inside the cluster network, not defending against a
 * MITM within that network. Same tradeoff as nexarank-api's identical
 * config and as Postgres's `sslmode=require` (encrypts, doesn't verify the
 * chain) — standing up a real internal CA/trust bundle is GCP-launch infra
 * work (NR-156), not this Kind dev cluster.
 */
@Configuration
@ConditionalOnProperty(name = "spring.data.redis.ssl.enabled", havingValue = "true")
public class RedisSslConfig {

    @Bean
    public LettuceClientConfigurationBuilderCustomizer lettuceSslCustomizer() {
        return builder -> builder.clientOptions(
                ClientOptions.builder()
                        .sslOptions(SslOptions.builder()
                                .trustManager(io.netty.handler.ssl.util.InsecureTrustManagerFactory.INSTANCE)
                                .build())
                        .build());
    }
}
